baseURL = ""
languageCode = "en-us"
title = "RÜTS"
pluralizeListTitles = false
disableKinds = [ ]
summaryLength = 40
enableRobotsTXT = true
paginate = 10
copyright = "All rights reserved."

[params]
  description = "Site description here."
  author = "Ruth Reyer"